version: '3.5'

services:
  ollama:
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    command: serve && pull llama3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code
    ports:
      - 80:80
    volumes:
      - ./app/:/code/app/
    env_file:
      - .env
    depends_on:
      - ollama